export SS′, LL′, AA′, RT, LP, SS′ART, SS′PART, SS′AA′RT, SS′L′ART, SS′PL′ART, SS′LL′AA′RT

const SS′ = (:state, :next_state)
const LL′ = (:legal_actions_mask, :next_legal_actions_mask)
const AA′ = (:action, :next_action)
const RT = (:reward, :terminal)
const LP = (:action_log_prob)
const SS′ART = (SS′..., :action, RT...)
const SS′PART = (SS′..., :action, :action_log_prob, RT...)
const SS′AA′RT = (SS′..., AA′..., RT...)
const SS′L′ART = (SS′..., :next_legal_actions_mask, :action, RT...)
const SS′PL′ART = (SS′..., :next_legal_actions_mask, :action, :action_log_prob, RT...)
const SS′LL′AA′RT = (SS′..., LL′..., AA′..., RT...)

include("sum_tree.jl")
include("CircularArraySARTSTraces.jl")
include("CircularArraySARTSATraces.jl")
include("CircularArraySLARTTraces.jl")
include("CircularPrioritizedTraces.jl")
include("common_elastic_array.jl")
include("ElasticArraySARTSTraces.jl")
include("ElasticArraySARTSATraces.jl")
include("ElasticArraySLARTTraces.jl")
